AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB Stack for Website Integration'

# ==================== PARAMETERS ====================
Parameters:
  EnvironmentName: 
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - staging
      - prod
    Description: Environment name for resource tagging

  TableName:
    Type: String
    Default: WebsiteData
    Description: Name of the DynamoDB table

  ReadCapacityUnits:
    Type:  Number
    Default:  5
    MinValue: 1
    MaxValue: 100
    Description:  Provisioned read capacity units

  WriteCapacityUnits:
    Type: Number
    Default: 5
    MinValue: 1
    MaxValue: 100
    Description: Provisioned write capacity units

  EnablePointInTimeRecovery:
    Type: String
    Default: 'false'
    AllowedValues: 
      - 'true'
      - 'false'
    Description: Enable point-in-time recovery for backups

Resources:
  # ==================== DYNAMODB TABLES ====================

  # Main table for storing website visitor/user data
  VisitorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${TableName}-Visitors-${EnvironmentName}'
      BillingMode:  PROVISIONED
      AttributeDefinitions: 
        # Primary key attributes
        - AttributeName: visitorId
          AttributeType: S
        - AttributeName:  visitTimestamp
          AttributeType: N
        # GSI attributes
        - AttributeName:  ipAddress
          AttributeType: S
      KeySchema:
        # Partition key - unique visitor ID
        - AttributeName: visitorId
          KeyType:  HASH
        # Sort key - timestamp for time-based queries
        - AttributeName: visitTimestamp
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits
      # Global Secondary Index for querying by IP address
      GlobalSecondaryIndexes: 
        - IndexName:  IPAddressIndex
          KeySchema: 
            - AttributeName:  ipAddress
              KeyType: HASH
            - AttributeName: visitTimestamp
              KeyType: RANGE
          Projection: 
            ProjectionType:  ALL
          ProvisionedThroughput: 
            ReadCapacityUnits: !Ref ReadCapacityUnits
            WriteCapacityUnits: !Ref WriteCapacityUnits
      # Time-to-live for automatic data expiration (optional)
      TimeToLiveSpecification: 
        AttributeName:  ttl
        Enabled: true
      # Point-in-time recovery for backups
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !Ref EnablePointInTimeRecovery
      # Server-side encryption
      SSESpecification: 
        SSEEnabled:  true
      Tags:
        - Key: Name
          Value: !Sub '${TableName}-Visitors-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName

  # Table for storing website content/pages
  ContentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${TableName}-Content-${EnvironmentName}'
      BillingMode: PAY_PER_REQUEST  # On-demand capacity for variable workloads
      AttributeDefinitions: 
        - AttributeName: pageId
          AttributeType: S
        - AttributeName: category
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: N
      KeySchema: 
        - AttributeName:  pageId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CategoryIndex
          KeySchema: 
            - AttributeName: category
              KeyType: HASH
            - AttributeName:  createdAt
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
      SSESpecification: 
        SSEEnabled:  true
      Tags:
        - Key: Name
          Value: !Sub '${TableName}-Content-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName

  # Table for user sessions
  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${TableName}-Sessions-${EnvironmentName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserSessionsIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Name
          Value: !Sub '${TableName}-Sessions-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName

  # Table for restaurant menu items
  MenuTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${TableName}-Menu-${EnvironmentName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: menuItemId
          AttributeType: S
        - AttributeName: category
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: menuItemId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: category
              KeyType: HASH
            - AttributeName: name
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Name
          Value: !Sub '${TableName}-Menu-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName

  # Table for restaurant table bookings
  BookingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${TableName}-Bookings-${EnvironmentName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: bookingId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: bookingDate
          AttributeType: S
        - AttributeName: tableNumber
          AttributeType: N
      KeySchema:
        - AttributeName: bookingId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserBookingsIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: bookingDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: DateTableIndex
          KeySchema:
            - AttributeName: bookingDate
              KeyType: HASH
            - AttributeName: tableNumber
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Name
          Value: !Sub '${TableName}-Bookings-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName

  # Table for restaurant tables management
  TablesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${TableName}-Tables-${EnvironmentName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tableId
          AttributeType: S
        - AttributeName: capacity
          AttributeType: N
      KeySchema:
        - AttributeName: tableId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CapacityIndex
          KeySchema:
            - AttributeName: capacity
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Name
          Value: !Sub '${TableName}-Tables-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName

  # Table for food orders
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${TableName}-Orders-${EnvironmentName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: orderDate
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserOrdersIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: orderDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: orderDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Name
          Value: !Sub '${TableName}-Orders-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName

  # AWS Learner Lab does not allow custom IAM role creation
  # Use LabRole: arn:aws:iam::<account-id>:role/LabRole
  # Use LabInstanceProfile: arn:aws:iam::<account-id>:instance-profile/LabInstanceProfile

  # ==================== SSM PARAMETERS ====================

  # Store table names in Parameter Store for easy retrieval
  VisitorsTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name:  !Sub '/website/${EnvironmentName}/dynamodb/visitors-table'
      Type: String
      Value: !Ref VisitorsTable
      Description: DynamoDB Visitors table name

  ContentTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub '/website/${EnvironmentName}/dynamodb/content-table'
      Type:  String
      Value:  !Ref ContentTable
      Description: DynamoDB Content table name

  SessionsTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/website/${EnvironmentName}/dynamodb/sessions-table'
      Type: String
      Value: !Ref SessionsTable
      Description: DynamoDB Sessions table name

  RegionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/website/${EnvironmentName}/dynamodb/region'
      Type: String
      Value: !Ref AWS::Region
      Description: AWS Region for DynamoDB

  MenuTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/website/${EnvironmentName}/dynamodb/menu-table'
      Type: String
      Value: !Ref MenuTable
      Description: DynamoDB Menu table name

  BookingsTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/website/${EnvironmentName}/dynamodb/bookings-table'
      Type: String
      Value: !Ref BookingsTable
      Description: DynamoDB Bookings table name

  TablesTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/website/${EnvironmentName}/dynamodb/tables-table'
      Type: String
      Value: !Ref TablesTable
      Description: DynamoDB Tables management table name

  OrdersTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/website/${EnvironmentName}/dynamodb/orders-table'
      Type: String
      Value: !Ref OrdersTable
      Description: DynamoDB Orders table name

  # ==================== AUTO SCALING (Optional) ====================

  # Read capacity auto scaling for Visitors table
  VisitorsTableReadScalingTarget:
    Type:  AWS::ApplicationAutoScaling::ScalableTarget
    Properties: 
      MaxCapacity: 100
      MinCapacity: 5
      ResourceId: !Sub 'table/${VisitorsTable}'
      RoleARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable'
      ScalableDimension:  dynamodb:table:ReadCapacityUnits
      ServiceNamespace: dynamodb

  VisitorsTableReadScalingPolicy:
    Type:  AWS::ApplicationAutoScaling::ScalingPolicy
    Properties: 
      PolicyName:  VisitorsTableReadAutoScaling
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref VisitorsTableReadScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization
        TargetValue: 70.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60

  # Write capacity auto scaling for Visitors table
  VisitorsTableWriteScalingTarget:
    Type:  AWS::ApplicationAutoScaling::ScalableTarget
    Properties: 
      MaxCapacity: 100
      MinCapacity: 5
      ResourceId: !Sub 'table/${VisitorsTable}'
      RoleARN:  !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable'
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      ServiceNamespace: dynamodb

  VisitorsTableWriteScalingPolicy: 
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: VisitorsTableWriteAutoScaling
      PolicyType: TargetTrackingScaling
      ScalingTargetId:  !Ref VisitorsTableWriteScalingTarget
      TargetTrackingScalingPolicyConfiguration: 
        PredefinedMetricSpecification: 
          PredefinedMetricType:  DynamoDBWriteCapacityUtilization
        TargetValue: 70.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60

# ==================== OUTPUTS ====================
Outputs:
  VisitorsTableName:
    Description:  Name of the Visitors DynamoDB table
    Value: !Ref VisitorsTable
    Export:
      Name:  !Sub '${AWS::StackName}-VisitorsTableName'

  VisitorsTableArn:
    Description: ARN of the Visitors DynamoDB table
    Value:  !GetAtt VisitorsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-VisitorsTableArn'

  ContentTableName: 
    Description: Name of the Content DynamoDB table
    Value: !Ref ContentTable
    Export: 
      Name: !Sub '${AWS::StackName}-ContentTableName'

  ContentTableArn: 
    Description: ARN of the Content DynamoDB table
    Value: !GetAtt ContentTable.Arn
    Export:
      Name:  !Sub '${AWS::StackName}-ContentTableArn'

  SessionsTableName:
    Description: Name of the Sessions DynamoDB table
    Value: !Ref SessionsTable
    Export:
      Name: !Sub '${AWS::StackName}-SessionsTableName'

  SessionsTableArn: 
    Description: ARN of the Sessions DynamoDB table
    Value: !GetAtt SessionsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SessionsTableArn'

  Region:
    Description:  AWS Region
    Value: !Ref AWS::Region
    
  LabRoleInfo:
    Description: Use LabRole for Lambda and EC2
    Value: "Get ARN with: aws iam get-role --role-name LabRole --query 'Role.Arn'"

  MenuTableName:
    Description: Name of the Menu DynamoDB table
    Value: !Ref MenuTable
    Export:
      Name: !Sub '${AWS::StackName}-MenuTableName'

  MenuTableArn:
    Description: ARN of the Menu DynamoDB table
    Value: !GetAtt MenuTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-MenuTableArn'

  BookingsTableName:
    Description: Name of the Bookings DynamoDB table
    Value: !Ref BookingsTable
    Export:
      Name: !Sub '${AWS::StackName}-BookingsTableName'

  BookingsTableArn:
    Description: ARN of the Bookings DynamoDB table
    Value: !GetAtt BookingsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BookingsTableArn'

  TablesTableName:
    Description: Name of the Tables management DynamoDB table
    Value: !Ref TablesTable
    Export:
      Name: !Sub '${AWS::StackName}-TablesTableName'

  TablesTableArn:
    Description: ARN of the Tables management DynamoDB table
    Value: !GetAtt TablesTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TablesTableArn'

  OrdersTableName:
    Description: Name of the Orders DynamoDB table
    Value: !Ref OrdersTable
    Export:
      Name: !Sub '${AWS::StackName}-OrdersTableName'

  OrdersTableArn:
    Description: ARN of the Orders DynamoDB table
    Value: !GetAtt OrdersTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-OrdersTableArn'
